api_platform:
    title: WR506 Movies and Actors API
    version: 1.0.0

    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_items_per_page: 5
        page_parameter_name: 'page'
        pagination_enabled: true
        items_per_page_parameter_name: 'itemsPerPage'

    graphql:
        collection:
            pagination:
                enabled: true

